### ISSUE TITLE
Start a wiki for high-level iOS todos

### ISSUE THREAD

**Issue by SyntaxBlitz** [language-transfer/lt-app#23]
What do we need to get done to get this thing built on iOS? Let's start a wiki page to write it all down in one place.

**Comment by schonfeld** [comment]
Linking with #27

**Comment by Alvynskio** [comment]
Is this still open? If it is, how can I help?

**Comment by SyntaxBlitz** [comment]
I don't think we need a wiki anymore, now that we've more-or-less handled the iOS transition. Closing this, thanks for flagging
